services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - database
    networks:
      - symfony_net

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    networks:
      - symfony_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"  # Expose phpMyAdmin on port 8080
    environment:
      PMA_HOST: database  # Specify the MySQL host
      PMA_USER: app       # MySQL user
      PMA_PASSWORD: app_password  # MySQL user password
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge